[project]
name = "hsbcparser"
version = "0.1.0"
description = "HSBC statement parser"
readme = "README.md"
requires-python = ">=3.10"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]